# Deployment da conversão de Peso
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meupod-peso
  labels:
    app: peso
spec:
  containers:
    - name: peso
      image: rodrigoturatti/conversao-peso:latest
      ports:
        - containerPort: 80
---
# Service do MongoDB
apiVersion: v1
kind: Service
metadata:
  name: peso
spec:
  selector:
    app: peso
  ports:
    - port: 80
  type: LoadBalancer